### ISSUE TITLE
[BUG] Scrolling breaks ride bar position (With Awesome UI plugin)

### ISSUE THREAD

**Issue by mathisgauthey** [YU000jp/logseq-plugin-left-sidebar-enhance#11] opened 2024-07-19 11:01 UTC
Hey there. There's currently two plugins creating a table of content on the left sidebar. Yours and [logseq-toc-plugin](https://github.com/benjypng/logseq-toc-plugin).

I got an issue with yours only, it scrolls down the right sidebar and I can't get back up afterward : 

![24_07_19-12_59_33-Logseq](https://github.com/user-attachments/assets/3dc30213-1982-4fbb-8ca7-7277dd5126fb)

**Comment by YU000jp** [comment] 2024-07-19 12:54
The bug is caused by interference from other plugins. One of the settings in "Awesome UI" plugin is affected - switch to Standard instead of Wide. This way, the bars will not overlap and cause anomalies.

On the plugin settings of Awesome UI
![image](https://github.com/user-attachments/assets/15921b61-9e3f-4903-aa77-f45735d8006f)

(My TOC product is actually more complex than TOC plugin, which look the same.  It works even if its parent block of the block with the header is closed. Headers generation process removes markdowns, properties, etc. It is then possible to delete specific strings. They should be merged, but this will not happen due to disagreements between producers.)

**Comment by mathisgauthey** [comment] 2024-07-19 13:32
Thanks for the detailed explanation !

The issue is still occurring after changing the setting you provided. It disappears if I don't use Awesome UI though.

**Closed** 2024-07-21 10:22 UTC
Labels: type: bug
